// Generated by gencpp from file serial_port/header.msg
// DO NOT EDIT!


#ifndef SERIAL_PORT_MESSAGE_HEADER_H
#define SERIAL_PORT_MESSAGE_HEADER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_port
{
template <class ContainerAllocator>
struct header_
{
  typedef header_<ContainerAllocator> Type;

  header_()
    : num1(0)
    , num2(0)
    , num3(0)  {
    }
  header_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)
    , num3(0)  {
  (void)_alloc;
    }



   typedef int16_t _num1_type;
  _num1_type num1;

   typedef int16_t _num2_type;
  _num2_type num2;

   typedef int16_t _num3_type;
  _num3_type num3;





  typedef boost::shared_ptr< ::serial_port::header_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_port::header_<ContainerAllocator> const> ConstPtr;

}; // struct header_

typedef ::serial_port::header_<std::allocator<void> > header;

typedef boost::shared_ptr< ::serial_port::header > headerPtr;
typedef boost::shared_ptr< ::serial_port::header const> headerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_port::header_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_port::header_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_port::header_<ContainerAllocator1> & lhs, const ::serial_port::header_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2 &&
    lhs.num3 == rhs.num3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_port::header_<ContainerAllocator1> & lhs, const ::serial_port::header_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_port

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_port::header_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_port::header_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_port::header_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_port::header_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port::header_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port::header_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_port::header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e2b57837792a4e2809b7e2db06c7c3c";
  }

  static const char* value(const ::serial_port::header_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e2b57837792a4e2ULL;
  static const uint64_t static_value2 = 0x809b7e2db06c7c3cULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_port::header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_port/header";
  }

  static const char* value(const ::serial_port::header_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_port::header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 num1\n"
"int16 num2\n"
"int16 num3\n"
;
  }

  static const char* value(const ::serial_port::header_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_port::header_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
      stream.next(m.num3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct header_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_port::header_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_port::header_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "num1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_PORT_MESSAGE_HEADER_H
